var link = document.createElement('a');
link.href = 'https://www.chandamama.in/resources/hindi/2013/Chandamama_Hindi_2013_01.pdf';
link.download = 'Chandamama_Hindi_2013_01.pdf';
link.click();
var link = document.createElement('a');
link.href = 'https://www.chandamama.in/resources/hindi/2013/Chandamama_Hindi_2013_02.pdf';
link.download = 'Chandamama_Hindi_2013_02.pdf';
link.click();
var link = document.createElement('a');
link.href = 'https://www.chandamama.in/resources/hindi/2013/Chandamama_Hindi_2013_03.pdf';
link.download = 'Chandamama_Hindi_2013_03.pdf';
link.click();
var link = document.createElement('a');
link.href = 'https://www.chandamama.in/resources/hindi/2013/Chandamama_Hindi_2013_04.pdf';
link.download = 'Chandamama_Hindi_2013_04.pdf';
link.click();
var link = document.createElement('a');
link.href = 'https://www.chandamama.in/resources/hindi/2013/Chandamama_Hindi_2013_05.pdf';
link.download = 'Chandamama_Hindi_2013_05.pdf';
link.click();
var link = document.createElement('a');
link.href = 'https://www.chandamama.in/resources/hindi/2013/Chandamama_Hindi_2013_06.pdf';
link.download = 'Chandamama_Hindi_2013_06.pdf';
link.click();
var link = document.createElement('a');
link.href = 'https://www.chandamama.in/resources/hindi/2013/Chandamama_Hindi_2013_07.pdf';
link.download = 'Chandamama_Hindi_2013_07.pdf';
link.click();
var link = document.createElement('a');
link.href = 'https://www.chandamama.in/resources/hindi/2013/Chandamama_Hindi_2013_08.pdf';
link.download = 'Chandamama_Hindi_2013_08.pdf';
link.click();
var link = document.createElement('a');
link.href = 'https://www.chandamama.in/resources/hindi/2013/Chandamama_Hindi_2013_09.pdf';
link.download = 'Chandamama_Hindi_2013_09.pdf';
link.click();
var link = document.createElement('a');
link.href = 'https://www.chandamama.in/resources/hindi/2013/Chandamama_Hindi_2013_10.pdf';
link.download = 'Chandamama_Hindi_2013_10.pdf';
link.click();
var link = document.createElement('a');
link.href = 'https://www.chandamama.in/resources/hindi/2013/Chandamama_Hindi_2013_11.pdf';
link.download = 'Chandamama_Hindi_2013_11.pdf';
link.click();
var link = document.createElement('a');
link.href = 'https://www.chandamama.in/resources/hindi/2013/Chandamama_Hindi_2013_12.pdf';
link.download = 'Chandamama_Hindi_2013_12.pdf';
link.click();

