[package]
name = "test_project"
version = "0.1.0"
edition = "2021"
test = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.8.1"

[[bin]]
name = "rust_test_new"
path = "src/rust_test_new.rs"
