let
qtr=(vdate as number)=>
    let
    input={
    {vdate>Number.From(#date(2020,12,31)) and vdate<Number.From(#date(2021,4,1)),"Q1:2021"},
    {vdate>Number.From(#date(2021,3,31)) and vdate<Number.From(#date(2021,7,1)),"Q2:2021"},
    {vdate>Number.From(#date(2021,6,30)) and vdate<Number.From(#date(2021,10,1)),"Q3:2021"},
    {vdate>Number.From(#date(2021,9,30)) and vdate<Number.From(#date(2022,1,1)),"Q4:2021"},
    {vdate>Number.From(#date(2021,12,31)) and vdate<Number.From(#date(2022,4,1)),"Q1:2022"},
    {vdate>Number.From(#date(2022,3,31)) and vdate<Number.From(#date(2022,7,1)),"Q2:2022"},
    {vdate>Number.From(#date(2022,6,30)) and vdate<Number.From(#date(2022,10,1)),"Q3:2022"},
    {vdate>Number.From(#date(2022,9,30)) and vdate<Number.From(#date(2023,1,1)),"Q4:2022"},
    {vdate>Number.From(#date(2022,12,31)) and vdate<Number.From(#date(2023,4,1)),"Q1:2023"},
    {Logical.From(vdate)=true,"Error"}   
    },
    output=List.First(List.Select(input,each _{0})){1}
    in
    output,
cum=(tbl as table) as table =>
    let
        #"Sorted"=Table.Sort(tbl,{{"Year",Order.Ascending},{"Transaction type",Order.Ascending}}),
        #"indexed"=Table.AddIndexColumn(#"Sorted","idx",1),
        #"cumulative"= Table.AddColumn(#"indexed","Running Total",each List.Accumulate(List.Range(#"indexed"[tr_count],0,[idx]),0,(state, current)=>state + current))
    in
        #"cumulative",
    Source = Csv.Document(File.Contents("M:\06830 - Content Dog LLC\Transaction List By Date 03_17_2023T02_40_54.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"cleaning up of amount" = Table.TransformColumns(Table.TransformColumns(#"Promoted Headers",{"Amount",each if _="--" then "0" else _}),{"Amount",each Text.Replace(_,"$","")}),
    #"Changed Type" = Table.TransformColumnTypes(#"cleaning up of amount",{{"Transaction date", type date}, {"Amount", type number}}),
    #"Transform Dates"=Table.TransformColumns(#"Changed Type",{"Transaction date", each Number.From(_)}),
    #"Added Custom" = Table.AddColumn(#"Transform Dates", "Quarter", each qtr([Transaction date])),
    #"Grouped Rows" = Table.Group(#"Added Custom", {"Quarter"}, {{"Count", each Table.RowCount(_), Int64.Type}})
in
    #"Grouped Rows"
