# Convert-WhatsApp.ps1
$inputFile = "D:\Downloads\WhatsApp Chat with Meta AI.txt"
$outputFile = "D:\Downloads\WhatsApp_Chat_with_Meta_AI.md"

Write-Host "Reading $inputFile ..."

$content = Get-Content -Path $inputFile -Raw -Encoding UTF8

# Split by new message start (date pattern like 26/06/24, )
$chunks = @()
$buf = ""
foreach ($line in $content -split "`n") {
    if ($line -match '^\d{1,2}/\d{1,2}/\d{2,4},\s+\d{1,2}:\d{2}.*[ap]m\s+-\s+') {
        if ($buf) { $chunks += $buf }
        $buf = $line + "`n"
    } else {
        $buf += $line + "`n"
    }
}
$chunks += $buf

$md = @()
$md += "# WhatsApp Chat with Meta AI"
$md += ""
$md += "> Converted from WhatsApp Export - $($chunks.Count) messages"
$md += ""
$md += "---"
$md += ""

foreach ($chunk in $chunks) {
    if ($chunk -match "Messages are generated by AI") { continue }
    if ($chunk -match "Unsupported message") { continue }
    
    $dash = $chunk.IndexOf(" - ")
    if ($dash -lt 0) { continue }
    $date = $chunk.Substring(0, $dash).Trim()
    $rest = $chunk.Substring($dash + 3)
    $colon = $rest.IndexOf(":")
    if ($colon -lt 0) { continue }
    
    $sender = $rest.Substring(0, $colon).Trim()
    $msg = $rest.Substring($colon + 1).Trim()
    if (-not $msg) { continue }

    if ($sender -like "*Dhawal*") {
        $md += "### 🧑 You"
        $md += "*$date*"
        $md += ""
        $md += $msg
        $md += ""
    } elseif ($sender -like "*Meta AI*") {
        $md += "### 🤖 Meta AI"
        $md += "*$date*"
        $md += ""
        $md += $msg
        $md += ""
        $md += "---"
        $md += ""
    }
}

$md -join "`n" | Set-Content -Path $outputFile -Encoding UTF8

Write-Host "Done! Saved to $outputFile"
Write-Host "Messages: $($chunks.Count)"
