"""
Consolidated xlwings UDF Module
Auto-generated by merge script
"""
import re
import xlwings as xw
import rdrand

@xw.func
@xw.arg('excel_range', ndim=2)
@xw.arg('patterns', ndim=1)
def REGEXFINDM(excel_range, patterns):
    result = []
    has_any_match = False
    
    for row in excel_range:
        row_result = []
        for cell in row:
            if cell is None or str(cell).strip() == "":
                row_result.append("")
                continue
                
            cell_str = str(cell)
            cell_result = []
            for pattern in patterns:
                match = re.search(pattern, cell_str, flags=re.UNICODE)
                if match:
                    cell_result.append(cell_str)
            
            if len(cell_result) == len(patterns):
                row_result.append(" ".join(cell_result))
                has_any_match = True
            else:
                row_result.append("")
        result.append(row_result)
    
    # Return empty if no matches found
    if not has_any_match:
        return [[""]]
    
    return result

@xw.func
def RDSEED_EXCEL(min_val, max_val, count):
    """Generate random numbers in range [min_val, max_val] using RDSEED."""
    count = int(count)
    min_val = int(min_val)
    max_val = int(max_val)
    
    s = rdrand.RdSeedom()  # Create instance once
    random_numbers = []
    
    for _ in range(count):
        random_number = s.get_bits(64) % (max_val - min_val + 1) + min_val
        random_numbers.append(random_number)
    
    return [[num] for num in random_numbers]
    
