# wa2docx.py  —  WhatsApp txt → docx  (no md intermediary)
# Usage: python wa2docx.py "D:\Downloads\WhatsApp Chat with Meta AI.txt" "D:\Downloads\WhatsApp_Chat.docx"

import sys, re, pathlib
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

IN  = sys.argv[1] if len(sys.argv) > 1 else r"D:\Downloads\WhatsApp Chat with Meta AI.txt"
OUT = sys.argv[2] if len(sys.argv) > 2 else r"D:\Downloads\WhatsApp_Chat.docx"

SKIP = re.compile(r"Messages are generated by AI|Unsupported message|end-to-end encrypted", re.I)
MSG  = re.compile(r'^(\d{1,2}/\d{1,2}/\d{2,4}),?\s+(\d{1,2}:\d{2}\s*[ap]m)\s+-\s+(.+?):\s+(.*)', re.I | re.S)
YOU  = re.compile(r'dhawal', re.I)

doc = Document()

# Tighten default paragraph spacing
style = doc.styles['Normal']
style.font.name = 'Calibri'
style.font.size = Pt(10)
pf = style.paragraph_format
pf.space_before = Pt(0)
pf.space_after  = Pt(2)

def add_heading(text, color_hex):
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(6)
    p.paragraph_format.space_after  = Pt(1)
    run = p.add_run(text)
    run.bold = True
    run.font.size = Pt(11)
    run.font.color.rgb = RGBColor(*(int(color_hex[i:i+2],16) for i in (0,2,4)))

def add_date(text):
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.space_after  = Pt(2)
    run = p.add_run(text)
    run.italic = True
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(120, 120, 120)

def add_body(text):
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        p = doc.add_paragraph(line)
        p.paragraph_format.space_before = Pt(0)
        p.paragraph_format.space_after  = Pt(1)

def add_divider():
    p = doc.add_paragraph('─' * 72)
    p.paragraph_format.space_before = Pt(4)
    p.paragraph_format.space_after  = Pt(4)
    p.runs[0].font.color.rgb = RGBColor(200, 200, 200)

# ── Parse & chunk ──────────────────────────────────────────────────────────────
raw   = pathlib.Path(IN).read_text(encoding='utf-8', errors='ignore')
lines = raw.splitlines()

chunks, buf = [], ""
for line in lines:
    if MSG.match(line):
        if buf: chunks.append(buf)
        buf = line + "\n"
    else:
        buf += line + "\n"
if buf: chunks.append(buf)

# ── Render ─────────────────────────────────────────────────────────────────────
count = 0
for chunk in chunks:
    chunk = chunk.strip()
    if not chunk or SKIP.search(chunk): continue
    m = MSG.match(chunk)
    if not m: continue
    date, time, sender, body = m.group(1), m.group(2), m.group(3), m.group(4)
    body = chunk[m.end():].strip() if not body.strip() else body + "\n" + chunk[m.end():]

    if YOU.search(sender):
        add_heading(f"🧑 You", "1565C0")
    elif re.search(r'meta.?ai', sender, re.I):
        add_heading(f"🤖 Meta AI", "2E7D32")
    else:
        add_heading(f"💬 {sender}", "555555")

    add_date(f"{date}  {time}")
    add_body(body)
    add_divider()
    count += 1

doc.save(OUT)
print(f"✓ Saved {count} messages → {OUT}")
